CREATE DATABASE loginDatabase; 

USE loginDatabase; 

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY, 
    email VARCHAR(255) NOT NULL UNIQUE, 
    password VARCHAR(255) NOT NULL, 
    profileComplete BOOLEAN DEFAULT FALSE, 
    created_at TIMESTAMP DEFAULT CURRENT_IMESTAMP, 
    updated_at TIMESTAMP CURRENT_IMESTAMP ON UPDATE CURRENT_IMESTAMP
); 